### ISSUE TITLE
Update Deno to 1.9.

### ISSUE THREAD

**Issue by Ayfri** [mayankchoubey/Deno-vs-Node-Performance#1]
In Deno 1.9, a lot of refactoring has been made, and they say that it improves performances from 68% to 98% (depends on the domain).
So it will be interesting to see the changes!

**Comment by mayankchoubey** [comment]
Sure, will be doing a new comparison soon.

**Comment by mayankchoubey** [comment]
@Ayfri  Thanks for your suggestion. I just finished the comparison. You can see the results in either of the places:

- https://github.com/mayankchoubey/Deno-vs-Node-Performance
- https://mayankchoubey.github.io/Deno-vs-Node-Performance

More suggestions are welcome!
