### ISSUE TITLE
ReqPerSec is inverted

### ISSUE THREAD

**Issue by antichris** [mayankchoubey/Deno-vs-Node-Performance#3]
*Requests per second* is a more-is-better measure. Right now there's "red"s where deno beats node and "green"s otherwise, which is inconsistent with all the other indicators.

- - -

Also, the stylesheet for github.io should have no padding or margin around the red/green `img`s in tables cells, e.g.:
```css
td>img {
	margin: 0;
	padding: 0;
}
```

**Comment by mayankchoubey** [comment]
@antichris  Good catch! I've corrected the req/sec.
